# Generated by Django 5.2.8 on 2026-05-12 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('date', models.DateField(db_index=True, verbose_name='统计日期')),
                ('total_questions', models.IntegerField(default=0, verbose_name='总提问数')),
                ('answered_questions', models.IntegerField(default=0, verbose_name='AI成功回答数')),
                ('rejected_questions', models.IntegerField(default=0, verbose_name='拒答数')),
                ('intercepted_questions', models.IntegerField(default=0, verbose_name='拦截数')),
                ('crisis_questions', models.IntegerField(default=0, verbose_name='危机干预数')),
                ('active_users', models.IntegerField(default=0, verbose_name='活跃用户数')),
                ('article_views', models.IntegerField(default=0, verbose_name='文章阅读量')),
                ('positive_feedbacks', models.IntegerField(default=0, verbose_name='好评数')),
                ('negative_feedbacks', models.IntegerField(default=0, verbose_name='差评数')),
                ('department', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='daily_stats', to='base.department', verbose_name='科室')),
            ],
            options={
                'verbose_name': '每日统计',
                'verbose_name_plural': '每日统计',
                'ordering': ['-date', '-department'],
                'unique_together': {('date', 'department')},
            },
        ),
    ]
