# Generated by Django 5.2.8 on 2026-05-12 15:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BrandConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('key', models.CharField(max_length=50, unique=True, verbose_name='配置键')),
                ('value', models.CharField(max_length=500, verbose_name='配置值')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='说明')),
            ],
            options={
                'verbose_name': '品牌配置',
                'verbose_name_plural': '品牌配置',
            },
        ),
        migrations.CreateModel(
            name='ConfigAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('CREATE', '创建'), ('UPDATE', '更新'), ('DELETE', '删除')], max_length=10, verbose_name='操作类型')),
                ('config_model', models.CharField(help_text='被修改的配置模型名称，如 LLMProviderConfig', max_length=100, verbose_name='配置模型')),
                ('config_target', models.CharField(help_text='被修改的配置标识，如配置名称或键名', max_length=200, verbose_name='操作目标')),
                ('performed_by', models.CharField(help_text='执行操作的用户名', max_length=150, verbose_name='操作人')),
                ('old_values', models.JSONField(blank=True, default=dict, help_text='修改前的配置值，敏感字段已掩码', verbose_name='修改前的值')),
                ('new_values', models.JSONField(blank=True, default=dict, help_text='修改后的配置值，敏感字段已掩码', verbose_name='修改后的值')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '配置审计日志',
                'verbose_name_plural': '配置审计日志',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmbeddingProviderConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='配置名称')),
                ('api_key', models.CharField(max_length=500, verbose_name='API Key')),
                ('base_url', models.URLField(max_length=500, verbose_name='服务地址')),
                ('model_name', models.CharField(max_length=100, verbose_name='模型名称')),
                ('dimensions', models.PositiveIntegerField(default=1024, help_text='Embedding 向量的维度，如 1024、1536、3072 等', verbose_name='向量维数')),
                ('provider', models.CharField(choices=[('openai', 'OpenAI'), ('custom', '自定义')], default='openai', max_length=20, verbose_name='提供商')),
                ('timeout', models.PositiveIntegerField(default=60, verbose_name='超时时间(秒)')),
                ('max_retries', models.PositiveIntegerField(default=3, verbose_name='最大重试次数')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='说明')),
            ],
            options={
                'verbose_name': 'Embedding 配置',
                'verbose_name_plural': 'Embedding 配置',
            },
        ),
        migrations.CreateModel(
            name='LLMProviderConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='配置名称')),
                ('api_key', models.CharField(max_length=500, verbose_name='API Key')),
                ('base_url', models.URLField(max_length=500, verbose_name='服务地址')),
                ('model_name', models.CharField(max_length=100, verbose_name='模型名称')),
                ('provider', models.CharField(choices=[('openai', 'OpenAI'), ('custom', '自定义')], default='openai', max_length=20, verbose_name='提供商')),
                ('timeout', models.PositiveIntegerField(default=60, verbose_name='超时时间(秒)')),
                ('max_retries', models.PositiveIntegerField(default=3, verbose_name='最大重试次数')),
                ('temperature', models.FloatField(default=0.1, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(2.0)], verbose_name='Temperature')),
                ('max_tokens', models.PositiveIntegerField(default=1024, verbose_name='最大输出Token数')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='说明')),
            ],
            options={
                'verbose_name': 'LLM 配置',
                'verbose_name_plural': 'LLM 配置',
            },
        ),
        migrations.CreateModel(
            name='PromptTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='模板名称')),
                ('content', models.TextField(help_text='支持变量替换，如 {{patient_context}}、{{department}}', verbose_name='模板内容')),
                ('is_default', models.BooleanField(default=False, help_text='同一时刻只能有一个活跃模板', verbose_name='是否活跃模板')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='说明')),
            ],
            options={
                'verbose_name': 'Prompt 模板',
                'verbose_name_plural': 'Prompt 模板',
                'ordering': ['-is_default', 'name'],
            },
        ),
        migrations.CreateModel(
            name='RAGConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('config_key', models.CharField(max_length=50, unique=True, verbose_name='配置项')),
                ('config_value', models.FloatField(verbose_name='配置值')),
                ('config_type', models.CharField(default='number', max_length=20, verbose_name='值类型')),
                ('category', models.CharField(choices=[('VECTOR', '向量参数'), ('CHUNK', '切片策略'), ('RETRIEVAL', '检索策略'), ('OPERATION', '文章运营')], max_length=20, verbose_name='分类')),
                ('min_value', models.FloatField(blank=True, null=True, verbose_name='最小值')),
                ('max_value', models.FloatField(blank=True, null=True, verbose_name='最大值')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='说明')),
            ],
            options={
                'verbose_name': 'RAG 配置',
                'verbose_name_plural': 'RAG 配置',
            },
        ),
        migrations.CreateModel(
            name='RateLimitRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('name', models.CharField(help_text='规则的唯一英文标识，如 anonymous、authenticated、login 等', max_length=50, unique=True, verbose_name='规则标识')),
                ('rule_type', models.CharField(choices=[('GLOBAL', '全局限流'), ('PATH', '路径限流'), ('SMS', '短信限流'), ('ANONYMOUS_CHAT', '匿名聊天限流')], max_length=20, verbose_name='规则类型')),
                ('path', models.CharField(blank=True, max_length=200, null=True, verbose_name='路径')),
                ('methods', models.JSONField(default=list, verbose_name='请求方法')),
                ('limit', models.PositiveIntegerField(verbose_name='限制次数')),
                ('window', models.PositiveIntegerField(verbose_name='时间窗口(秒)')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='说明')),
            ],
            options={
                'verbose_name': '限流规则',
                'verbose_name_plural': '限流规则',
                'ordering': ['rule_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='RerankProviderConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='配置名称')),
                ('api_key', models.CharField(max_length=500, verbose_name='API Key')),
                ('base_url', models.URLField(max_length=500, verbose_name='服务地址')),
                ('model_name', models.CharField(max_length=100, verbose_name='模型名称')),
                ('top_n', models.PositiveIntegerField(default=5, help_text='Rerank API 默认返回的文档数量', verbose_name='默认返回数量')),
                ('provider', models.CharField(choices=[('openai', 'OpenAI'), ('custom', '自定义')], default='openai', max_length=20, verbose_name='提供商')),
                ('timeout', models.PositiveIntegerField(default=60, verbose_name='超时时间(秒)')),
                ('max_retries', models.PositiveIntegerField(default=3, verbose_name='最大重试次数')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='说明')),
            ],
            options={
                'verbose_name': 'Rerank 配置',
                'verbose_name_plural': 'Rerank 配置',
            },
        ),
        migrations.CreateModel(
            name='SafetyRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('rule_type', models.CharField(choices=[('DANGEROUS_OUTPUT', '危险输出模式'), ('SIMILARITY_THRESHOLD', '相似度阈值'), ('REJECTION_MESSAGE', '拒答话术'), ('EMERGENCY_RESPONSE', '紧急响应话术'), ('SAFETY_WARNING', '安全警告话术')], max_length=30, verbose_name='规则类型')),
                ('rule_key', models.CharField(max_length=50, unique=True, verbose_name='规则标识')),
                ('rule_value', models.JSONField(verbose_name='规则值')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='说明')),
            ],
            options={
                'verbose_name': '安全规则',
                'verbose_name_plural': '安全规则',
            },
        ),
        migrations.CreateModel(
            name='SensitiveWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('word', models.CharField(max_length=50, unique=True, verbose_name='敏感词')),
                ('category', models.CharField(choices=[('SUICIDE', '自杀自残'), ('EMERGENCY', '紧急医疗'), ('DRUG', '药物剂量'), ('DIAGNOSIS', '诊断治疗')], max_length=20, verbose_name='分类')),
            ],
            options={
                'verbose_name': '敏感词',
                'verbose_name_plural': '敏感词',
                'ordering': ['category', 'word'],
            },
        ),
        migrations.CreateModel(
            name='TestConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('name', models.CharField(max_length=50)),
                ('value', models.CharField(blank=True, default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='SystemConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('NETWORK', '网络配置'), ('SESSION', '会话管理'), ('TASK', '任务队列'), ('BRAND', '品牌信息'), ('SMS', '短信服务')], max_length=30, verbose_name='分类')),
                ('config_key', models.CharField(max_length=100, verbose_name='配置键')),
                ('config_value', models.JSONField(verbose_name='配置值')),
                ('is_encrypted', models.BooleanField(default=False, verbose_name='是否加密')),
                ('requires_restart', models.BooleanField(default=False, verbose_name='需重启生效')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='说明')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '系统配置',
                'verbose_name_plural': '系统配置',
                'unique_together': {('category', 'config_key')},
            },
        ),
    ]
