// Package tests_test 提供 API 契约文件自动生成（P0-4b）。
//
// 生成内容：路由表 + 鉴权分级 + 域 + Handler 源码位置（file:line）。
// 前端据此锁定调用方法，进入 handler 函数体即可看到请求体/响应体的 json 解码与写出。
//
// 设计原则：
//   - 真自动生成，零手维护注册表——chi.Walk 遍历路由树，runtime 反射拿 handler 源码位置。
//   - 不反射 schema 副本——Go struct + json tag 本身就是真相，副本必然 drift。
//   - 不可能 drift：handler 改了，源码链接自动跟着变。
package tests_test

import (
	"net/http"
	"os"
	"path/filepath"
	"reflect"
	"regexp"
	"runtime"
	"sort"
	"strings"
	"testing"
	"time"

	"github.com/go-chi/chi/v5"

	"health-nexus/internal/shared/constants"
)

// pathParamPattern 匹配 {id} 形式的路径参数，用于探针请求时替换成合法值。
var pathParamPattern = regexp.MustCompile(`\{[^}]+\}`)

func TestGenerateAPIContract(t *testing.T) {
	entries := collectRoutes(t)
	if len(entries) == 0 {
		t.Fatal("no routes collected from testRouter")
	}

	out := buildMarkdown(entries)

	outDir := filepath.Join("..", "docs")
	if err := os.MkdirAll(outDir, 0o755); err != nil {
		t.Fatalf("create docs dir: %v", err)
	}
	outPath := filepath.Join(outDir, "api-contract.md")
	if err := os.WriteFile(outPath, []byte(out), 0o644); err != nil {
		t.Fatalf("write api-contract.md: %v", err)
	}
	t.Logf("API contract written to %s (%d endpoints)", outPath, len(entries))
}

type contractEntry struct {
	Method  string
	Path    string
	Auth    string
	Domain  string
	Handler handlerRef
}

type handlerRef struct {
	FuncName string // runtime 函数名，如 health-nexus/.../handler.(*AuthHandler).UnifiedLogin
	File     string // 源码文件绝对路径
	Line     int    // 源码行号
}

// collectRoutes 遍历 testRouter 路由树，收集每个端点的元信息。
func collectRoutes(t *testing.T) []contractEntry {
	t.Helper()
	router, ok := testRouter.(chi.Router)
	if !ok {
		t.Fatalf("testRouter is %T, expected chi.Router for Walk", testRouter)
	}

	seen := make(map[string]struct{})
	var entries []contractEntry
	err := chi.Walk(router, func(method, route string, handler http.Handler, _ ...func(http.Handler) http.Handler) error {
		key := method + " " + route
		if _, dup := seen[key]; dup {
			return nil
		}
		seen[key] = struct{}{}
		entries = append(entries, contractEntry{
			Method:  method,
			Path:    route,
			Auth:    probeAuthLevel(method, route),
			Domain:  domainOf(route),
			Handler: reflectHandler(handler),
		})
		return nil
	})
	if err != nil {
		t.Fatalf("walk router: %v", err)
	}

	sort.Slice(entries, func(i, j int) bool {
		if entries[i].Path != entries[j].Path {
			return entries[i].Path < entries[j].Path
		}
		return entries[i].Method < entries[j].Method
	})
	return entries
}

// reflectHandler 从 chi.Walk 交出的 http.Handler 反射出方法值对应的函数名。
// handler 通常是一个 http.HandlerFunc 包装的方法值。
// Go 对方法值生成的 funcval 经 runtime.FuncForPC 解析得到名字形如
// "health-nexus/.../handler.(*AuthHandler).UnifiedLogin-fm"——含完整限定名 + "-fm" 后缀。
// file:line 为 <autogenerated>:1（thunk 无真实源码位置），故只保留函数名。
// 闭包（如 /healthz 的内联 handler）拿到的则是真实调用点 file:line。
func reflectHandler(h http.Handler) handlerRef {
	hv := reflect.ValueOf(h)
	pc := hv.Pointer()
	if pc == 0 {
		return handlerRef{FuncName: "(inline handler)"}
	}
	fc := runtime.FuncForPC(pc)
	if fc == nil {
		return handlerRef{FuncName: "(unknown)"}
	}
	name := fc.Name()
	file, line := fc.FileLine(pc)
	// 方法值后缀 -fm 去掉，得到干净的限定名。
	name = strings.TrimSuffix(name, "-fm")
	// thunk 的 file 是 <autogenerated>，不输出链接，仅保留函数名。
	if file == "" || file == "<autogenerated>" {
		return handlerRef{FuncName: name}
	}
	return handlerRef{
		FuncName: name,
		File:     file,
		Line:     line,
	}
}

// probeAuthLevel 通过探针请求探测端点的鉴权等级。
// 依次用无 token / patient token / doctor token 请求，根据 401/403 组合判定 public/authenticated/patient/staff/admin。
func probeAuthLevel(method, route string) string {
	probePath := pathParamPattern.ReplaceAllString(route, "1")

	if code := doRequest(method, probePath, "").Code; code != http.StatusUnauthorized {
		return "public"
	}
	patientCode := doRequest(method, probePath, signTestToken(1, constants.RolePatient, 0)).Code
	doctorCode := doRequest(method, probePath, signTestToken(1, constants.RoleDoctor, 100)).Code

	patientDenied := patientCode == http.StatusForbidden
	doctorDenied := doctorCode == http.StatusForbidden
	switch {
	case patientDenied && doctorDenied:
		return "admin"
	case patientDenied:
		return "staff"
	case doctorDenied:
		return "patient"
	default:
		return "authenticated"
	}
}

// authDesc 把内部鉴权标记映射成 Markdown 表里的中文显示。
func authDesc(auth string) string {
	switch auth {
	case "public":
		return "公开"
	case "authenticated":
		return "已登录 (任意角色)"
	case "staff":
		return "医护 (STAFF)"
	case "patient":
		return "患者 (PATIENT)"
	case "admin":
		return "管理员 (SUPER_ADMIN/DEPT_ADMIN)"
	default:
		return auth
	}
}

// domainOf 按路径前缀归类端点所属业务域，用于 Markdown 表的"域"列分组。
func domainOf(route string) string {
	switch {
	case route == "/healthz":
		return "health"
	case strings.HasPrefix(route, "/api/staff/auth"):
		return "auth-admin"
	case strings.HasPrefix(route, "/api/auth"):
		return "auth"
	case strings.HasPrefix(route, "/api/staff/base"):
		return "base-admin"
	case strings.HasPrefix(route, "/api/base"):
		return "base"
	case strings.HasPrefix(route, "/api/staff/wiki"):
		return "wiki-staff"
	case strings.HasPrefix(route, "/api/wiki"):
		return "wiki-public"
	case strings.HasPrefix(route, "/api/staff/chat"):
		return "chat-staff"
	case strings.HasPrefix(route, "/api/chat"):
		return "chat-patient"
	case strings.HasPrefix(route, "/api/staff/config"):
		return "config"
	default:
		return "other"
	}
}

// buildMarkdown 把路由表渲染成 Markdown。Handler 列给出 file:// 链接，前端可直接点进去看请求体/响应体类型。
func buildMarkdown(entries []contractEntry) string {
	var b strings.Builder
	b.WriteString("# health-nexus 后端 API 契约\n\n")
	b.WriteString("> 本文件由门禁自动生成（`tests/api_contract_gen_test.go` → `chi.Walk` 遍历路由树 + `runtime` 反射 handler 源码位置）。\n")
	b.WriteString("> 每次运行门禁覆盖更新，始终与后端代码同步。前端可据此锁定 handler，进入函数体即见请求体/响应体的 json 解码与写出。\n\n")
	b.WriteString("- 生成时间（UTC）：")
	b.WriteString(time.Now().UTC().Format(time.RFC3339))
	b.WriteString("\n- 端点总数：")
	b.WriteString(itoa(len(entries)))
	b.WriteString("\n\n## 鉴权分级说明\n\n")
	b.WriteString("| 标记 | 含义 |\n|------|------|\n")
	b.WriteString("| 公开 | 无需认证 |\n")
	b.WriteString("| 已登录 (任意角色) | 需 `Authorization: Bearer <access>`，任意角色可访问 |\n")
	b.WriteString("| 医护 (STAFF) | 需 JWT + 医护角色（SUPER_ADMIN/DEPT_ADMIN/DOCTOR/NURSE） |\n")
	b.WriteString("| 患者 (PATIENT) | 需 JWT + 患者角色 |\n")
	b.WriteString("| 管理员 (SUPER_ADMIN/DEPT_ADMIN) | 需 JWT + 管理员角色 |\n\n")
	b.WriteString("## 端点清单\n\n")
	b.WriteString("| # | 方法 | 路径 | 鉴权 | 域 | Handler (源码) |\n")
	b.WriteString("|---|------|------|------|----|----------------|\n")
	for i, e := range entries {
		b.WriteString("| ")
		b.WriteString(itoa(i + 1))
		b.WriteString(" | ")
		b.WriteString(e.Method)
		b.WriteString(" | `")
		b.WriteString(e.Path)
		b.WriteString("` | ")
		b.WriteString(authDesc(e.Auth))
		b.WriteString(" | ")
		b.WriteString(e.Domain)
		b.WriteString(" | ")
		b.WriteString(handlerLink(e.Handler))
		b.WriteString(" |\n")
	}
	return b.String()
}

// handlerLink 渲染 Handler 列单元格。
// 有 file:line（闭包 handler）→ 给 file:// 链接。
// 仅有函数名（方法值 thunk）→ 显示完整限定名，并用反引号包裹便于 IDE 全局搜索。
func handlerLink(h handlerRef) string {
	if h.FuncName == "" {
		return "(unknown)"
	}
	if h.File != "" {
		return "[" + shortHandlerName(h.FuncName) + "](file:///" + filepath.ToSlash(h.File) + "#L" + itoa(h.Line) + ")"
	}
	return "`" + h.FuncName + "`"
}

// shortHandlerName 从完整限定名提取短显示名。
// "health-nexus/.../handler.(*AuthHandler).UnifiedLogin" → "AuthHandler.UnifiedLogin"
// "health-nexus/tests_test.func1" → "func1"
func shortHandlerName(full string) string {
	// 处理 receiver 形式：pkg.(*Type).Method
	if idx := strings.Index(full, "(*"); idx >= 0 {
		rest := full[idx+2:] // 跳过 "(*"
		if c := strings.Index(rest, ")"); c >= 0 {
			typeName := rest[:c]
			method := strings.TrimPrefix(rest[c+1:], ".")
			return typeName + "." + method
		}
	}
	// 普通形式：取最后一段
	if idx := strings.LastIndex(full, "."); idx >= 0 {
		return full[idx+1:]
	}
	return full
}

// itoa 最小整数转字符串，避免引入 strconv 仅此一处。
func itoa(n int) string {
	if n == 0 {
		return "0"
	}
	neg := n < 0
	if neg {
		n = -n
	}
	var buf [20]byte
	i := len(buf)
	for n > 0 {
		i--
		buf[i] = byte('0' + n%10)
		n /= 10
	}
	if neg {
		i--
		buf[i] = '-'
	}
	return string(buf[i:])
}
