# Generated by Django 5.2.8 on 2026-05-12 15:52

import apps.wiki.models
import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.deletion
import django_quill.fields
import pgvector.django.vector
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('summary', models.CharField(blank=True, help_text='用于列表页展示，留空自动截取', max_length=300, verbose_name='摘要')),
                ('cover_image', models.ImageField(blank=True, upload_to='articles/covers/', validators=[apps.wiki.models.validate_cover_image], verbose_name='封面图')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='阅读量')),
                ('content', django_quill.fields.QuillField(help_text='用于前端完整展示', verbose_name='HTML内容')),
                ('status', models.CharField(choices=[('DRAFT', '草稿'), ('PENDING', '待审核'), ('PUBLISHED', '已发布'), ('ARCHIVED', '已下线')], default='DRAFT', max_length=20, verbose_name='状态')),
                ('source_type', models.CharField(choices=[('MANUAL', '人工撰写'), ('AI_IMPORT', 'AI导入')], default='MANUAL', max_length=20, verbose_name='来源')),
                ('version', models.PositiveIntegerField(default=1, help_text='每次修改已发布文章版本号递增', verbose_name='版本号')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='软删除')),
                ('review_due_date', models.DateField(blank=True, null=True, verbose_name='复审日期')),
                ('review_overdue', models.BooleanField(default=False, help_text='到期后保持发布但标记待复核', verbose_name='复审已到期')),
                ('allow_reference', models.BooleanField(default=False, help_text='是否允许子科室引用此公共文章', verbose_name='允许引用')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='作者')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.department', verbose_name='所属科室')),
            ],
            options={
                'verbose_name': '宣教文章',
                'verbose_name_plural': '宣教文章',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ArticleAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(blank=True, choices=[('DRAFT', '草稿'), ('PENDING', '待审核'), ('PUBLISHED', '已发布'), ('ARCHIVED', '已下线')], max_length=20, null=True, verbose_name='变更前状态')),
                ('new_status', models.CharField(choices=[('DRAFT', '草稿'), ('PENDING', '待审核'), ('PUBLISHED', '已发布'), ('ARCHIVED', '已下线')], max_length=20, verbose_name='变更后状态')),
                ('reason', models.TextField(blank=True, default='', verbose_name='变更原因')),
                ('change_summary', models.TextField(blank=True, default='', help_text='编辑时记录变更内容摘要', verbose_name='变更内容摘要')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='变更时间')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='wiki.article', verbose_name='关联文章')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='操作用户')),
            ],
            options={
                'verbose_name': '文章审计日志',
                'verbose_name_plural': '文章审计日志',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ArticleChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_text', models.TextField(help_text='清洗了HTML标签的文本，用于喂给大模型', verbose_name='纯文本切片')),
                ('embedding', pgvector.django.vector.VectorField(dimensions=1024, verbose_name='向量数据')),
                ('chunk_index', models.IntegerField(default=0, verbose_name='切片序号')),
                ('version', models.PositiveIntegerField(default=1, help_text='所属文章版本号', verbose_name='版本号')),
                ('is_active', models.BooleanField(default=True, help_text='当前生效的切片', verbose_name='生效中')),
                ('content_hash', models.CharField(blank=True, default='', help_text='用于检测内容是否变化', max_length=32, verbose_name='内容哈希')),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(blank=True, help_text='PostgreSQL 全文搜索向量，用于 BM25 检索', null=True, verbose_name='全文搜索向量')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='wiki.article', verbose_name='源文章')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.department', verbose_name='冗余科室ID')),
            ],
            options={
                'verbose_name': '知识切片',
                'verbose_name_plural': '知识切片',
                'indexes': [models.Index(fields=['department'], name='idx_chunk_dept'), models.Index(fields=['article', 'chunk_index'], name='idx_article_chunk'), django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='idx_chunk_search_vector')],
            },
        ),
        migrations.CreateModel(
            name='ArticleReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', '待审核'), ('APPROVED', '已授权'), ('REJECTED', '已拒绝'), ('INVALIDATED', '已失效'), ('REVOKED', '已撤销')], default='PENDING', max_length=20, verbose_name='审核状态')),
                ('authorized_at', models.DateTimeField(blank=True, null=True, verbose_name='授权时间')),
                ('reason', models.TextField(blank=True, default='', verbose_name='拒绝原因')),
                ('invalidated_at', models.DateTimeField(blank=True, help_text='源文章更新时自动设置', null=True, verbose_name='失效时间')),
                ('invalidated_reason', models.CharField(blank=True, default='', max_length=200, verbose_name='失效原因')),
                ('revoked_at', models.DateTimeField(blank=True, null=True, verbose_name='撤销时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('approved_by_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_article_references', to='base.department', verbose_name='审批科室')),
                ('authorized_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='授权人')),
                ('revoked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revoked_article_references', to=settings.AUTH_USER_MODEL, verbose_name='撤销人')),
                ('source_article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='references_to', to='wiki.article', verbose_name='被引用文章')),
                ('target_department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_references', to='base.department', verbose_name='引用科室')),
            ],
            options={
                'verbose_name': '文章引用',
                'verbose_name_plural': '文章引用',
                'ordering': ['-created_at'],
                'unique_together': {('source_article', 'target_department')},
            },
        ),
    ]
