# Generated by Django 6.0.1 on 2026-05-13 01:51

import apps.wiki.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=apps.wiki.models.ForgivingQuillField(help_text='用于前端完整展示', verbose_name='HTML内容'),
        ),
    ]
