# Generated by Django 5.2.8 on 2026-05-12 15:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='科室名称')),
                ('description', models.TextField(blank=True, verbose_name='科室描述')),
                ('is_public', models.BooleanField(default=False, help_text='公共空间的知识对所有科室可见', verbose_name='是否公共空间')),
                ('config', models.JSONField(blank=True, default=dict, help_text="如：{'welcome_msg': '您好，心内科助手为您服务'}", verbose_name='科室配置')),
                ('tenant_code', models.CharField(blank=True, default='', max_length=50, verbose_name='租户编码')),
                ('is_active', models.BooleanField(default=True, help_text='禁用后该科室将不可见', verbose_name='是否启用')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_departments', to=settings.AUTH_USER_MODEL, verbose_name='科室主任')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='base.department', verbose_name='上级科室')),
            ],
            options={
                'verbose_name': '科室',
                'verbose_name_plural': '科室',
            },
        ),
        migrations.CreateModel(
            name='DepartmentAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('action_type', models.CharField(max_length=50, verbose_name='操作类型')),
                ('target', models.CharField(blank=True, default='', max_length=200, verbose_name='操作目标')),
                ('details', models.JSONField(blank=True, default=dict, verbose_name='详细信息')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='base.department', verbose_name='科室')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
            ],
            options={
                'verbose_name': '审计日志',
                'verbose_name_plural': '审计日志',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('category', models.CharField(choices=[('CRISIS', '危机事件'), ('REVIEW', '复审提醒'), ('SYSTEM', '系统通知')], max_length=20, verbose_name='类别')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('content', models.TextField(blank=True, default='', verbose_name='内容')),
                ('is_read', models.BooleanField(db_index=True, default=False, verbose_name='已读')),
                ('related_url', models.URLField(blank=True, default='', max_length=500, verbose_name='相关链接')),
                ('source_id', models.CharField(blank=True, default='', help_text='关联的业务对象ID', max_length=100, verbose_name='来源ID')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='接收人')),
            ],
            options={
                'verbose_name': '通知',
                'verbose_name_plural': '通知',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read'], name='idx_notif_recipient_read')],
            },
        ),
        migrations.CreateModel(
            name='UserDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('role', models.CharField(choices=[('ADMIN', '管理员'), ('MEMBER', '成员'), ('VIEWER', '只读成员')], default='MEMBER', max_length=20, verbose_name='角色')),
                ('is_primary', models.BooleanField(default=False, verbose_name='是否主科室')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_departments', to='base.department', verbose_name='科室')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_departments', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户科室关系',
                'verbose_name_plural': '用户科室关系',
                'unique_together': {('department', 'user')},
            },
        ),
    ]
