# Generated by Django 5.2.8 on 2026-05-12 15:52

import django.db.models.deletion
import encrypted_model_fields.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=50, verbose_name='真实姓名')),
                ('id_number', encrypted_model_fields.fields.EncryptedCharField(blank=True, null=True, verbose_name='身份证号 (加密)')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='出生日期')),
                ('gender', models.CharField(blank=True, choices=[('M', '男'), ('F', '女'), ('O', '其他')], max_length=10, verbose_name='性别')),
                ('height', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='身高 (cm)')),
                ('weight', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='体重 (kg)')),
                ('education', models.CharField(blank=True, choices=[('primary', '小学'), ('junior', '初中'), ('senior', '高中/中专'), ('college', '大专'), ('bachelor', '本科'), ('master', '硕士'), ('doctor', '博士'), ('other', '其他')], default='', max_length=20, verbose_name='文化程度')),
                ('marital_status', models.CharField(blank=True, choices=[('single', '未婚'), ('married', '已婚'), ('divorced', '离异'), ('widowed', '丧偶')], default='', max_length=10, verbose_name='婚姻状况')),
                ('occupation', models.CharField(blank=True, default='', max_length=50, verbose_name='职业')),
                ('blood_type', models.CharField(blank=True, choices=[('A', 'A型'), ('B', 'B型'), ('AB', 'AB型'), ('O', 'O型'), ('unknown', '未知')], default='', max_length=10, verbose_name='血型')),
                ('phone', models.CharField(blank=True, default='', max_length=20, verbose_name='联系电话')),
                ('address', models.CharField(blank=True, default='', max_length=200, verbose_name='家庭住址')),
                ('emergency_contact', models.CharField(blank=True, default='', max_length=50, verbose_name='紧急联系人')),
                ('emergency_phone', models.CharField(blank=True, default='', max_length=20, verbose_name='紧急联系电话')),
                ('medical_history_summary', encrypted_model_fields.fields.EncryptedCharField(blank=True, help_text='如：高血压3年，糖尿病2年', null=True, verbose_name='既往病史摘要')),
                ('allergies_summary', encrypted_model_fields.fields.EncryptedCharField(blank=True, null=True, verbose_name='过敏史摘要')),
                ('departments', models.ManyToManyField(help_text='AI回答时会优先检索这些科室的知识库', related_name='patients', to='base.department', verbose_name='就诊科室')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='patient_profile', to=settings.AUTH_USER_MODEL, verbose_name='关联账号')),
            ],
            options={
                'verbose_name': '患者档案',
                'verbose_name_plural': '患者档案',
            },
        ),
        migrations.CreateModel(
            name='MedicationRecord',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='记录ID')),
                ('medication_name', models.CharField(max_length=200, verbose_name='药品名称')),
                ('dosage', models.CharField(blank=True, help_text='如 500mg', max_length=200, verbose_name='剂量')),
                ('frequency', models.CharField(blank=True, help_text='如 每日2次', max_length=200, verbose_name='频次')),
                ('route', models.CharField(blank=True, choices=[('oral', '口服'), ('iv', '静脉注射'), ('sc', '皮下注射'), ('im', '肌肉注射'), ('topical', '外用'), ('inhalation', '吸入'), ('other', '其他')], max_length=20, verbose_name='给药途径')),
                ('start_date', models.DateField(verbose_name='开始用药日期')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='停药日期')),
                ('status', models.CharField(choices=[('active', '正在服用'), ('paused', '暂停'), ('stopped', '已停药')], default='active', max_length=20, verbose_name='状态')),
                ('prescriber', models.CharField(blank=True, max_length=200, verbose_name='开药医生/医院')),
                ('notes', models.TextField(blank=True, help_text='副作用、注意事项等', verbose_name='备注')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medications', to='care.patientprofile', verbose_name='所属患者')),
            ],
            options={
                'verbose_name': '用药记录',
                'verbose_name_plural': '用药记录',
                'ordering': ['-start_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LabTestRecord',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='记录ID')),
                ('test_date', models.DateField(verbose_name='检查日期')),
                ('source', models.CharField(blank=True, max_length=100, verbose_name='医院名称')),
                ('lab_type', models.CharField(choices=[('blood_routine', '血常规'), ('biochemistry', '生化全套'), ('urine_routine', '尿常规'), ('thyroid_function', '甲状腺功能'), ('hba1c', '糖化血红蛋白'), ('other', '其他')], max_length=30, verbose_name='检验类型')),
                ('data', models.JSONField(blank=True, default=dict, help_text="如 {'WBC': 6.5, 'HGB': 145, 'PLT': 200}", verbose_name='检验指标')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_tests', to='care.patientprofile', verbose_name='所属患者')),
            ],
            options={
                'verbose_name': '检验报告',
                'verbose_name_plural': '检验报告',
                'ordering': ['-test_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ImagingRecord',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='记录ID')),
                ('exam_date', models.DateField(verbose_name='检查日期')),
                ('source', models.CharField(blank=True, max_length=100, verbose_name='医院名称')),
                ('imaging_type', models.CharField(choices=[('ct', 'CT'), ('mri', 'MRI'), ('xray', 'X光'), ('ultrasound', '超声'), ('ecg', '心电图'), ('other', '其他')], max_length=20, verbose_name='检查类型')),
                ('body_part', models.CharField(blank=True, max_length=100, verbose_name='检查部位')),
                ('findings', models.TextField(blank=True, help_text='影像描述', verbose_name='检查所见')),
                ('conclusion', models.TextField(blank=True, verbose_name='诊断结论')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imaging_records', to='care.patientprofile', verbose_name='所属患者')),
            ],
            options={
                'verbose_name': '影像检查',
                'verbose_name_plural': '影像检查',
                'ordering': ['-exam_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VitalSignRecord',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='记录ID')),
                ('record_date', models.DateField(verbose_name='测量日期')),
                ('record_time', models.TimeField(blank=True, null=True, verbose_name='测量时间')),
                ('source', models.CharField(blank=True, help_text='设备名称/医院', max_length=100, verbose_name='来源')),
                ('systolic_bp', models.IntegerField(blank=True, help_text='正常范围: 90-140', null=True, verbose_name='收缩压 (mmHg)')),
                ('diastolic_bp', models.IntegerField(blank=True, help_text='正常范围: 60-90', null=True, verbose_name='舒张压 (mmHg)')),
                ('heart_rate', models.IntegerField(blank=True, help_text='正常范围: 60-100', null=True, verbose_name='心率 (次/分)')),
                ('pulse', models.IntegerField(blank=True, help_text='正常范围: 60-100', null=True, verbose_name='脉搏 (次/分)')),
                ('temperature', models.DecimalField(blank=True, decimal_places=1, help_text='正常范围: 36.1-37.2', max_digits=4, null=True, verbose_name='体温 (°C)')),
                ('respiratory_rate', models.IntegerField(blank=True, help_text='正常范围: 12-20', null=True, verbose_name='呼吸频率 (次/分)')),
                ('blood_glucose', models.DecimalField(blank=True, decimal_places=1, help_text='正常范围: 3.9-6.1 (空腹)', max_digits=4, null=True, verbose_name='血糖 (mmol/L)')),
                ('blood_oxygen', models.IntegerField(blank=True, help_text='正常范围: 95-100', null=True, verbose_name='血氧饱和度 (%)')),
                ('weight', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='体重 (kg)')),
                ('height', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='身高 (cm)')),
                ('bmi', models.DecimalField(blank=True, decimal_places=1, help_text='可自动计算', max_digits=4, null=True, verbose_name='BMI')),
                ('pain_score', models.IntegerField(blank=True, help_text='0=无痛, 10=剧痛', null=True, verbose_name='疼痛得分 (NRS 0-10)')),
                ('measurement_context', models.CharField(blank=True, choices=[('fasting', '空腹'), ('post_meal', '餐后'), ('resting', '静息'), ('post_exercise', '运动后'), ('other', '其他')], max_length=50, verbose_name='测量场景')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vital_signs', to='care.patientprofile', verbose_name='所属患者')),
            ],
            options={
                'verbose_name': '生命体征记录',
                'verbose_name_plural': '生命体征记录',
                'ordering': ['-record_date', '-record_time', '-created_at'],
            },
        ),
    ]
