# Generated by Django 5.2.8 on 2026-05-12 15:52

import apps.auth.models
import django.contrib.auth.validators
import django.utils.timezone
import encrypted_model_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('SUPER_ADMIN', '超级管理员'), ('DEPT_ADMIN', '科室管理员'), ('DOCTOR', '医生'), ('NURSE', '护士'), ('PATIENT', '患者')], default='PATIENT', max_length=20, verbose_name='角色')),
                ('phone', encrypted_model_fields.fields.EncryptedCharField(blank=True, verbose_name='手机号 (加密)')),
                ('phone_hash', models.CharField(blank=True, db_index=True, default='', help_text='手机号 SHA-256 哈希，用于快速查找', max_length=64, null=True, verbose_name='手机号哈希')),
                ('current_session_key', models.CharField(blank=True, help_text='单设备单会话限制，新登录会覆盖旧会话', max_length=128, null=True, unique=True, verbose_name='当前会话 key')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='头像')),
                ('login_alert_enabled', models.BooleanField(default=True, verbose_name='登录提醒开关')),
                ('health_data_share_enabled', models.BooleanField(default=True, verbose_name='健康数据共享开关')),
                ('agreed_terms', models.BooleanField(default=False, help_text='患者首次登录必须同意免责条款', verbose_name='是否同意免责条款')),
                ('agreed_terms_at', models.DateTimeField(blank=True, null=True, verbose_name='同意条款时间')),
                ('settings', models.JSONField(blank=True, default=dict, help_text='用户偏好设置: theme, language, notification_enabled, font_size', verbose_name='用户偏好设置')),
                ('bind_qr_code', models.CharField(blank=True, help_text='用户专属绑定二维码标识，注册时自动生成', max_length=64, null=True, unique=True, verbose_name='绑定二维码标识')),
                ('title', models.CharField(blank=True, choices=[('doctor', '医生'), ('nurse', '护士'), ('medical_technician', '医技')], default='', max_length=20, verbose_name='职称')),
                ('bio', models.TextField(blank=True, default='', help_text='医生/护士个人专业背景介绍', verbose_name='个人简介')),
            ],
            options={
                'verbose_name': '用户账户',
                'verbose_name_plural': '用户账户',
            },
            managers=[
                ('objects', apps.auth.models.UserProfileManager()),
            ],
        ),
        migrations.CreateModel(
            name='PatientDoctorBinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initiator', models.CharField(choices=[('PATIENT', '患者'), ('DOCTOR', '医护')], default='DOCTOR', help_text='绑定请求发起方', max_length=10)),
                ('status', models.CharField(choices=[('PENDING', '待确认'), ('CONFIRMED', '已绑定'), ('REJECTED', '已拒绝'), ('REVOKED', '已解绑')], default='PENDING', help_text='绑定状态', max_length=20)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': '医患绑定',
                'verbose_name_plural': '医患绑定',
                'ordering': ['-requested_at'],
            },
        ),
    ]
