# Generated by Django 5.2.8 on 2026-05-12 15:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0001_initial'),
        ('auth_custom', '0001_initial'),
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='departments',
            field=models.ManyToManyField(help_text='用户所属的多个科室', related_name='users', through='base.UserDepartment', to='base.department', verbose_name='关联科室'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AddField(
            model_name='patientdoctorbinding',
            name='doctor',
            field=models.ForeignKey(limit_choices_to={'role__in': ['DOCTOR', 'NURSE']}, on_delete=django.db.models.deletion.CASCADE, related_name='patient_bindings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='patientdoctorbinding',
            name='patient',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'PATIENT'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doctor_bindings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='patientdoctorbinding',
            unique_together={('patient', 'doctor')},
        ),
    ]
