"""
服务接口契约定义

基于 SOLID 原则设计的接口层：
- ISP: 每个接口只包含单一职责的方法，客户端不被迫依赖不需要的接口
- LSP: 接口使用 Django Model 类型而非 Stub，确保实现可安全替换
- DIP: 高层模块依赖这些抽象接口，而非具体实现
"""

from typing import Protocol, List, Dict, Optional, Tuple, Any, TYPE_CHECKING

if TYPE_CHECKING:
    from apps.base.models import Department
    from apps.auth.models import UserProfile
    from apps.care.models import PatientProfile
    from apps.wiki.models import Article, ArticleChunk
    from apps.chat.models import Conversation, Message


class IDepartmentService(Protocol):
    def get_public_departments(self) -> List['Department']: ...
    def get_user_departments(self, user) -> List['Department']: ...
    def get_all_departments(self, exclude_public: bool = False) -> List['Department']: ...
    def get_department_by_id(self, dept_id: int) -> Optional['Department']: ...
    def create_department(self, data: Dict, user=None) -> 'Department': ...
    def update_department(self, dept_id: int, data: Dict, user=None) -> 'Department': ...
    def delete_department(self, dept_id: int, user=None) -> bool: ...
    def get_department_tree(self) -> List[Dict]: ...
    def add_member(self, dept_id: int, user_id: int, role: str, is_primary: bool = False, actor=None) -> Any: ...
    def remove_member(self, dept_id: int, user_id: int, actor=None) -> bool: ...
    def get_members(self, dept_id: int) -> List[Dict]: ...


class IUserService(Protocol):
    def get_user_by_id(self, user_id: int) -> Optional['UserProfile']: ...
    def check_permission(self, user, action: str, resource_type: str, resource_id: int = None) -> bool: ...
    def get_users_by_department(self, department_id: int, role: str = None) -> List['UserProfile']: ...
    def get_user_by_phone(self, phone: str) -> Optional['UserProfile']: ...


class IUserSettingsService(Protocol):
    def bind_phone(self, user, phone: str, code: str) -> bool: ...
    def unbind_phone(self, user, code: str) -> bool: ...
    def update_security_settings(self, user, **kwargs) -> bool: ...
    def update_privacy_settings(self, user, **kwargs) -> bool: ...
    def export_user_data(self, user) -> Dict[str, Any]: ...
    def update_avatar(self, user, avatar_file: Any) -> bool: ...
    def get_user_preferences(self, user) -> Dict[str, Any]: ...
    def update_user_preferences(self, user, preferences: Dict[str, Any]) -> bool: ...
    def record_login_device(self, user, ip: str, user_agent: str) -> None: ...


class ILoginSecurityService(Protocol):
    def handle_failed_login(self, username: str) -> None: ...
    def increment_failed_attempts(self, user_id: int) -> None: ...
    def clear_failed_attempts(self, user_id: int) -> None: ...
    def is_account_locked(self, user_id: int) -> bool: ...
    def get_failed_attempts(self, user_id: int) -> int: ...
    def get_lock_remaining_minutes(self, user_id: int) -> int: ...
    def handle_failed_login_by_phone(self, phone: str) -> None: ...


class ISMSService(Protocol):
    def send_code(self, phone: str, ip: str) -> Dict[str, Any]: ...
    def verify_code(self, phone: str, code: str) -> bool: ...


class IPatientCRUDService(Protocol):
    def get_patient_profile(self, user) -> Optional['PatientProfile']: ...
    def get_patient_profile_by_user(self, user) -> Optional['PatientProfile']: ...
    def get_patients_by_department(self, department_id: int) -> List['PatientProfile']: ...


class IPatientContextService(Protocol):
    def get_patient_context(self, patient: 'PatientProfile') -> Dict[str, Any]: ...


class IKnowledgeSearchService(Protocol):
    def search_similar_chunks(
        self,
        query: str,
        departments: List['Department'] = None,
        top_k: int = 3
    ) -> List['ArticleChunk']: ...

    def generate_embedding(self, text: str) -> List[float]: ...


class IWikiService(Protocol):
    def create_article(
        self,
        title: str,
        content: str,
        author,
        department,
        source_type: str = 'MANUAL',
    ) -> 'Article': ...

    def submit_for_review(self, article: 'Article', user) -> 'Article': ...

    def review_article(
        self,
        article: 'Article',
        reviewer,
        action: str,
        reason: str = "",
    ) -> 'Article': ...

    def update_article(self, article, user, title: str = None, content: str = None, department=None) -> 'Article': ...

    def change_article_status(self, article: 'Article', user, new_status: str) -> 'Article': ...

    def delete_draft(self, article: 'Article', user) -> 'Article': ...

    def soft_delete_article(self, article: 'Article', user) -> 'Article': ...


class IRAGService(Protocol):
    def rag_retrieve(
        self,
        query: str,
        patient: Optional['PatientProfile'] = None,
        selected_departments: List['Department'] = None,
        health_data_share_enabled: bool = True,
    ) -> Tuple[str, List['ArticleChunk']]: ...


class IChatManagementService(Protocol):
    def create_conversation(self, patient: 'PatientProfile', title: str = None) -> 'Conversation': ...
    def save_message(self, conversation, sender, content, reference_chunks=None, feedback: int = 0) -> 'Message': ...
    def update_feedback(self, message_id: int, feedback: int, reason: str = None) -> 'Message': ...
    def get_disliked_messages(self, department_id: int = None, limit: int = 50) -> list: ...
    def get_conversation_history(self, conversation_id, patient=None) -> Tuple: ...


class IStatsService(Protocol):
    def get_knowledge_coverage(self, start_date=None, end_date=None, department_id=None) -> dict: ...
    def get_feedback_stats(self, start_date=None, end_date=None, department_id=None) -> dict: ...
    def get_daily_stats(self, days: int = 30, department_id=None) -> list: ...
    def get_department_stats(self) -> list: ...
    def get_user_activity(self, days: int = 30) -> dict: ...
    def get_article_view_stats(self, start_date=None, end_date=None, department_id=None, limit: int = 10) -> dict: ...
    def aggregate_daily_stats(self, target_date=None) -> dict: ...


class IChatSendService(Protocol):
    def send_message(self, message: str, user, conversation_id: Optional[str], selected_dept_ids: List[str], session_key: Optional[str] = None) -> Any: ...
    def get_ai_response_stream(self, message: str, patient: Optional['PatientProfile'], selected_departments: List['Department'], conversation_id: Optional[str] = None) -> Tuple: ...
    def save_ai_message_streaming(self, conversation: Optional['Conversation'], relevant_chunks: List[Any]) -> Optional['Message']: ...
    def finalize_ai_message(self, ai_message: 'Message', answer: str, relevant_chunks: List[Any]) -> None: ...
    def release_lock(self, lock_key: str) -> None: ...


class IFeedbackService(Protocol):
    def submit_feedback(self, message_id: int, user, feedback_value: int, reason: str = '') -> Any: ...
    def get_disliked_messages_with_details(self, department_id: int = None, limit: int = 100) -> list: ...


class IVitalSignService(Protocol):
    def get_vital_signs(self, patient_id: int) -> list: ...
    def get_vital_signs_by_patient(self, patient) -> list: ...
    def add_vital_sign(self, patient_id: int, data: dict) -> Any: ...
    def create_vital_sign(self, patient, data: dict) -> Any: ...
    def delete_vital_sign(self, record_id: int, user) -> None: ...
    def get_latest_vital_signs(self, patient_id: int) -> dict: ...


class ILabTestService(Protocol):
    def get_lab_tests(self, patient_id: int) -> list: ...
    def get_lab_tests_by_patient(self, patient) -> list: ...
    def add_lab_test(self, patient_id: int, data: dict) -> Any: ...
    def create_lab_test(self, patient, data: dict) -> Any: ...
    def delete_lab_test(self, record_id: int, user) -> None: ...


class IImagingService(Protocol):
    def get_imaging_records(self, patient_id: int) -> list: ...
    def get_imaging_by_patient(self, patient) -> list: ...
    def add_imaging_record(self, patient_id: int, data: dict) -> Any: ...
    def create_imaging(self, patient, data: dict) -> Any: ...
    def delete_imaging(self, record_id: int, user) -> None: ...


class IMedicationService(Protocol):
    def get_medications(self, patient_id: int) -> list: ...
    def get_medication_history(self, patient) -> list: ...
    def get_current_medications(self, patient) -> list: ...
    def add_medication(self, patient_id: int, data: dict) -> Any: ...
    def create_medication(self, patient, data: dict) -> Any: ...
    def update_medication(self, medication_id: int, data: dict) -> Any: ...
    def discontinue_medication(self, medication_id: int, reason: str = '') -> Any: ...
    def stop_medication(self, record_id: int, user, end_date=None) -> None: ...
    def resume_medication(self, record_id: int, user) -> None: ...
    def delete_medication(self, record_id: int, user) -> None: ...


class IMedicalRecordAggregator(Protocol):
    def get_all_records(self, patient, limit: int = 50) -> List[dict]: ...


class IArticleReferenceService(Protocol):
    def get_references_for_article(self, article_id: int) -> list: ...
    def add_reference(self, article_id: int, data: dict) -> Any: ...
    def reference_article(self, article_id: int, dept_id: int, user=None) -> Tuple[bool, str]: ...
    def approve_reference(self, article_id: int, dept_id: int, user=None) -> Tuple[bool, str]: ...
    def reject_reference(self, article_id: int, dept_id: int, reason: str = '', user=None) -> Tuple[bool, str]: ...
    def get_available_public_articles(self, dept_id: int) -> list: ...


class IAuditLogService(Protocol):
    def log_action(self, department, user, action_type: str, target: str = '', details: dict = None) -> Any: ...
    def get_recent_logs(self, department_id: int = None, limit: int = 50) -> list: ...


class IBindingService(Protocol):
    def generate_user_qr(self, user_id: int) -> Tuple[str, str]: ...
    def resolve_user_by_qr(self, qr_code: str) -> Optional[Dict]: ...
    def create_binding_request(self, target_user_id: int, initiator_user_id: int, initiator_type: str) -> Tuple[bool, str]: ...
    def confirm_binding(self, binding_id: int, user_id: int) -> Tuple[bool, str]: ...
    def reject_binding(self, binding_id: int, user_id: int) -> Tuple[bool, str]: ...
    def get_pending_requests_for_user(self, user_id: int) -> list: ...
    def get_confirmed_bindings_for_doctor(self, user_id: int) -> list: ...
    def get_confirmed_bindings_for_patient(self, user_id: int) -> list: ...


class IBulkImportService(Protocol):
    def import_from_excel(self, file, user) -> Any: ...


class IStaffDashboardService(Protocol):
    def get_dashboard_context(self, user, request) -> Dict: ...


class ILLMClientProtocol(Protocol):
    def generate(self, system: str, query: str) -> str: ...
