# Generated by Django 5.2.8 on 2026-05-12 15:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
        ('care', '0001_initial'),
        ('wiki', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_key', models.CharField(blank=True, db_index=True, max_length=40)),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='会话标题')),
                ('is_archived', models.BooleanField(db_index=True, default=False, verbose_name='已归档')),
                ('archived_at', models.DateTimeField(blank=True, null=True, verbose_name='归档时间')),
                ('departments', models.ManyToManyField(blank=True, related_name='conversations', to='base.department', verbose_name='锁定科室')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='care.patientprofile')),
            ],
            options={
                'verbose_name': 'AI会话',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='HotQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('question', models.CharField(max_length=200, verbose_name='问题')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hot_questions', to='base.department', verbose_name='所属科室')),
            ],
            options={
                'verbose_name': '热门问题',
                'verbose_name_plural': '热门问题',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('sender', models.CharField(choices=[('USER', '用户'), ('AI', 'AI助手')], max_length=10)),
                ('content', models.TextField(verbose_name='内容')),
                ('processing_result', models.CharField(choices=[('ANSWERED', '已回答'), ('REJECTED', '拒答'), ('INTERCEPTED', '拦截'), ('CRISIS', '危机'), ('RATE_LIMITED', '限流')], db_index=True, default='ANSWERED', max_length=20, verbose_name='处理结果')),
                ('is_streaming', models.BooleanField(db_index=True, default=False, verbose_name='是否生成中')),
                ('is_safety_flagged', models.BooleanField(db_index=True, default=False, verbose_name='是否触发安全检测')),
                ('safety_flag_reason', models.CharField(blank=True, default='', max_length=200, verbose_name='安全标记原因')),
                ('safety_flag_level', models.CharField(blank=True, default='', max_length=20, verbose_name='安全标记级别')),
                ('original_content', models.TextField(blank=True, default='', verbose_name='截断前原始内容')),
                ('feedback', models.IntegerField(choices=[(0, '未评价'), (1, '有用'), (-1, '无用/错误')], default=0, verbose_name='用户评价')),
                ('feedback_reason', models.CharField(blank=True, choices=[('INACCURATE', '回答不准确'), ('INCOMPLETE', '回答不完整'), ('IRRELEVANT', '回答不相关'), ('UNSAFE', '内容不安全'), ('OTHER', '其他')], max_length=20, verbose_name='差评原因')),
                ('review_status', models.IntegerField(choices=[(0, '待处理'), (1, '已处理'), (2, '需修正')], default=0, verbose_name='处理状态')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='审核时间')),
                ('correction_status', models.CharField(choices=[('NONE', '无需修正'), ('PENDING', '待修正'), ('IN_PROGRESS', '修正中'), ('DONE', '已修正'), ('VERIFIED', '已验证')], default='NONE', max_length=20, verbose_name='修正状态')),
                ('correction_note', models.TextField(blank=True, default='', verbose_name='修正备注')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.conversation')),
                ('reference_chunks', models.ManyToManyField(blank=True, to='wiki.articlechunk', verbose_name='引用切片')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='审核人')),
            ],
            options={
                'verbose_name': '对话消息',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='CrisisEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('level', models.CharField(choices=[('CRISIS', '自伤危机'), ('EMERGENCY', '紧急症状')], max_length=20, verbose_name='危机级别')),
                ('trigger_text', models.TextField(blank=True, default='', verbose_name='触发内容')),
                ('matched_keywords', models.CharField(blank=True, default='', max_length=200, verbose_name='匹配关键词')),
                ('is_resolved', models.BooleanField(db_index=True, default=False, verbose_name='已处理')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='处理时间')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crisis_events', to='chat.conversation', verbose_name='关联会话')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crisis_events', to='care.patientprofile', verbose_name='患者')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_crisis_events', to=settings.AUTH_USER_MODEL, verbose_name='处理人')),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crisis_events', to='chat.message', verbose_name='关联消息')),
            ],
            options={
                'verbose_name': '危机事件',
                'verbose_name_plural': '危机事件',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PromptTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('type', models.CharField(choices=[('SYSTEM', '系统提示词'), ('REJECTION', '拒答消息'), ('EMERGENCY', '紧急情况响应'), ('SAFETY_WARNING', '安全警告')], max_length=20, verbose_name='模板类型')),
                ('content', models.TextField(verbose_name='模板内容')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
            ],
            options={
                'verbose_name': 'Prompt模板',
                'verbose_name_plural': 'Prompt模板',
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('type',), name='unique_active_prompt_per_type')],
            },
        ),
    ]
